name: Deploy Musk Tracker to Azure

on:
  push:
    branches: [ main ]
    paths: [ 'Musk_Watcher/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'Musk_Watcher/musk-tracker-app/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd Musk_Watcher/musk-tracker-app
        npm ci
        
    - name: Build application
      run: |
        cd Musk_Watcher/musk-tracker-app
        npm run build
        
name: Deploy Musk Tracker to Azure

on:
  push:
    branches: [ main ]
    paths: [ 'Musk_Watcher/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'Musk_Watcher/musk-tracker-app/package-lock.json'
        
    - name: Install dependencies and build
      run: |
        cd Musk_Watcher/musk-tracker-app
        npm install
        npm run build
        
    - name: Create deployment package
      run: |
        cd Musk_Watcher/musk-tracker-app
        zip -r deployment.zip . -x "*.git*" "node_modules/.cache/*" "src/*"
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'ActualMust'
        package: './Musk_Watcher/musk-tracker-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
