# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ActualMusk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    permissions:
      contents: read #This is required for actions/checkout
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd Musk_Watcher/musk-tracker-app
          npm install
          npm run build --if-present
          npm run test --if-present      - name: Zip artifact for deployment
        run: |
          cd Musk_Watcher/musk-tracker-app
          echo "Files before zipping:"
          ls -la
          echo "Dist folder contents:"
          ls -la dist/
          zip -r ../../release.zip ./* -x "node_modules/.cache/*" "src/*" ".git/*"
          echo "Release zip created:"
          ls -la ../../release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          echo "Files after unzipping:"
          ls -la
          echo "Checking for key files:"
          ls -la package.json || echo "package.json not found"
          ls -la dist/ || echo "dist folder not found"
          ls -la dist/app.js || echo "dist/app.js not found"
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ActualMusk'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D638D30F87C44B4B099D6E3061E269F }}